### PR TITLE
Remove admin bar from frontend

### PR DESCRIPTION
**Pull request by jankeesvw**
Fix this error: 

image

### CODE REVIEW

**Comment by jankeesvw** [comment]
@inlet is this the code to fix the issue?

**Comment by inlet** [comment]
Should work! Haven't tested it but looks like the admin bar is loaded in frontend. Why need one.

**Comment by inlet** [comment]
:+1:

**Comment by epologee** [comment]
Thank you!

**Comment by jankeesvw** [comment]
Good new, it works:

image

**Pull request merged**
